Introduce Error Codes
uber/h3-go pull request #63
Opened 2023-12-01 21:51 UTC by charlespnh

2023-12-01 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/h3-go?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/h3-go?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/h3-go?pullRequest=63) it.</sub>

2023-12-02 20:25 UTC, jogly requested changes
thank you so much for your contribution, its looking great! there are only a few v small fixups needed to merge this.  after you address comments, appease the linter, and run the files through `gofmt` it will be g2g!

2023-12-02 20:25 UTC, jogly commented on h3.go
> +var H3ErrorFailed = errors.New("Unknown error")
In addition to the following lint warnings, can you group them in a var block like
```go
var (
  ErrFailed = ...
  ErrDomain = ...
  ..
)
```

and update the error messages to start lowercase 
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

2023-12-02 20:25 UTC, jogly commented on h3.go
> +func New(errc int) error {
```suggestion
func errFromCode(errc int) error {
```

suggest unexport the error mapper as it is not relevant to consumers and rename to reflect that it maps from h3 error codes from C to Go

2023-12-02 20:25 UTC, jogly commented on h3.go
> +	return Cell(i), nil
You can inline the check into the conditional:

```go
if rc := C.latLngToCell(latLng.toCPtr(), C.int(resolution), &i); rc != C.E_SUCCESS {
  return Cell(-1), errFromCode(int(rc))
}
return Cell(i), nil
```

I've also renamed `errc` to `rc` as it is a return code, not necessarily an error.

---

It's a fun idea to introduce sentinel values `Cell(-1)`, but the error we return is sufficient signal that we can keep the amount of change low by continuing to return empty/undefined values on error.

2023-12-02 20:25 UTC, jogly commented on h3.go
> +var _ = H3ErrorInvalidOption
whats going on here?

2023-12-02 20:25 UTC, jogly commented on h3_test.go
> +func testDirectedEdgeError(t *testing.T) {
```suggestion

func TestDirectedEdgeError(t *testing.T) {
```

2023-12-02 20:25 UTC, jogly commented on h3_test.go
> +	assertTrue(t, errors.Is(err, H3ErrorInvalidDirEdge))
can you pop the literal addresses into a named fixture var at the top of the file, similar to the other fixture vars? it helps us keep a handle on what these values mean.

2024-03-10 18:43 UTC, jogly approved these changes

2024-12-27 22:32 UTC, zachcoleman commented
#73 now does this

2024-12-27 22:32 UTC, closed without merging